# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255, verbose_name='Заголовок поста')),
            ],
            options={
                'verbose_name_plural': 'Записи',
                'verbose_name': 'Запись',
            },
        ),
    ]
