# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='', verbose_name='Запись'),
        ),
    ]
