# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=255, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
